services:
  minecraft:
    image: itzg/minecraft-server
    container_name: paper-mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "PAPER"
      MEMORY: "3G"
      MAX_MEMORY: "5G"
      EULA: "TRUE"
      ONLINE_MODE: "TRUE"
      SERVER_NAME: "LC-EssentialX"
      MOTD: "§6Welcome to the Server! §eHave fun! §b🎮"
      OVERRIDE_ICON: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
    volumes:
      - /home/lance-c/paper-mc/:/data
    restart: unless-stopped