services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "TRUE"
      TYPE: PAPER
      SYNC_SKIP_NEWER_IN_DESTINATION: false
      MEMORY: "3G"
      MAX_MEMORY: "5G"
      MOTD: "§6Welcome to the Server! §eHave fun! §b🎮"
      OVERRIDE_ICON: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
    volumes:
      - ./home/lance-c/paper-mc/:/data
      - ./paper-global.yml:/config/paper-global.yml
  proxy:
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./velocity.toml:/config/velocity.toml:ro
      - ./forwarding.secret:/config/forwarding.secret:ro
      - proxy:/server

volumes:
  proxy: {}
